
export const BASE_URL = process.env.BASE_URL

export const GHOST_URL = process.env.GHOST_URL
export const GHOST_KEY = process.env.GHOST_KEY

export const GITHUB_TOKEN  = process.env.GITHUB_TOKEN

export const NEXT_PUBLIC_GITHUB_REPO = process.env.NEXT_PUBLIC_GITHUB_REPO
export const NEXT_PUBLIC_GITHUB_REPO_ID  = process.env.NEXT_PUBLIC_GITHUB_REPO_ID
export const NEXT_PUBLIC_GITHUB_CATEGORY = process.env.NEXT_PUBLIC_GITHUB_CATEGORY
export const NEXT_PUBLIC_GITHUB_CATEGORY_ID  = process.env.NEXT_PUBLIC_GITHUB_CATEGORY_ID

export const CONTENTFUL_SPACE_ID = process.env.CONTENTFUL_SPACE_ID
export const CONTENTFUL_DELIVERY_API = process.env.CONTENTFUL_DELIVERY_API
export const CONTENTFUL_PREVIEW_API = process.env.CONTENTFUL_PREVIEW_API

export const NEXT_PUBLIC_ALGOLIA_API = process.env.NEXT_PUBLIC_ALGOLIA_API
export const NEXT_PUBLIC_ALGOLIA_APP = process.env.NEXT_PUBLIC_ALGOLIA_APP
export const NEXT_PUBLIC_ALGOLIA_INDEX = process.env.NEXT_PUBLIC_ALGOLIA_INDEX


export const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET