import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import Header from "@/components/layout/header";
import Main from "@/components/layout/main";
import Footer from "@/components/layout/footer";

import "./reset.css";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSans.className}>
        <Header className="juji-header"/>
        <Main className="juji-main">{children}</Main>
        <Footer className="juji-footer" />
      </body>
    </html>
  );
}
