import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import Header from "@/components/layout/header";
import Main from "@/components/layout/main";
import Footer from "@/components/layout/footer";
import { Toaster } from 'react-hot-toast';

import "./reset.css";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* https://nextjs.org/docs/messages/react-hydration-error */}
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
      </head>
      <body className={workSans.className}>
        <Header className="juji-header"/>
        <Main className="juji-main">{children}</Main>
        <Footer className="juji-footer" />
        <Toaster 
          toastOptions={{
            style: {
              background: '#212121',
              color: '#fff',
              padding: '1rem',
              maxWidth: 'unset'
            }
          }}
        />
      </body>
    </html>
  );
}
