import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import Header from "@/components/layout/header";
import Main from "@/components/layout/main";
import Footer from "@/components/layout/footer";
import { Toaster } from 'react-hot-toast';

import "./reset.css";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        {/* <!-- Google Tag Manager --> */}
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-WXVPD642');</script>
        {/* <!-- End Google Tag Manager --> */}

        {/* https://nextjs.org/docs/messages/react-hydration-error */}
        <meta
          name="format-detection"
          content="telephone=no, date=no, email=no, address=no"
        />
      </head>
      <body className={workSans.className}>

      {/* <!-- Google Tag Manager (noscript) --> */}
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WXVPD642"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      {/* <!-- End Google Tag Manager (noscript) --> */}

        <Header className="juji-header"/>
        <Main className="juji-main">{children}</Main>
        <Footer className="juji-footer" />
        <Toaster 
          toastOptions={{
            style: {
              background: '#99e500',
              color: '#000000',
              padding: '0.6rem 1rem',
              maxWidth: 'unset'
            }
          }}
        />
      </body>
    </html>
  );
}
